### ISSUE TITLE
Implement progress bar

### ISSUE THREAD

**Issue by loelschlaeger** [loelschlaeger/fHMM#41]
Write own code for progress + ETA output. Remove dependence to "progress" package.

**Comment by RouvenM** [comment]
Own Progress Bar has been added (yet still local, but we can change on Monday). Did not work directly, since I had to adapt and change some data structure and control structure. For example, the following problems occured:

**Comment by RouvenM** [comment]
-	"Data" is somehow unclear, as sometimes data[[„source“]] is specified in sandbox but data[[„data“]] is necassery (e.g., in optimized)
-	Data (which I downloaded) hat values „none“ instead of „NA“, wherefore those values did not disappear when I wanted to created starting values
-	Data is loaded as character. I had to use as.numeric then
-	Normally, Runs will be set to 100 in check.controls – unfortunately, it set it to 50 (I had to change manually then) - but maybe that might be due to my mistake in the code djungel ;-)
